notifications:
  commits:      private@security.apache.org
  issues:       private@security.apache.org
  pullrequests: private@security.apache.org
  discussions:  private@security.apache.org

staging:
  profile: ~

publish:
  whoami: asf-site
  
