baseURL = 'https://security.apache.org/'
languageCode = 'en-us'
title = 'Apache Security Team'
theme = 'kube'
markup.goldmark.renderer.unsafe = true
markup.goldmark.parser.attribute.block = true
[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 10
[[menu.main]]
    name = "License"
    url = "https://www.apache.org/licenses/"
    weight = 20
[[menu.main]]
    name = "Sponsorship"
    url = "https://www.apache.org/foundation/sponsorship.html"
    weight = 30
[[menu.main]]
    name = "Thanks"
    url = "https://www.apache.org/foundation/thanks.html"
    weight = 40
[[menu.main]]
    name = "Privacy"
    url = "https://privacy.apache.org/policies/privacy-policy-public.html"
    weight = 50
[[menu.main]]
    name = "Apache"
    url = "https://www.apache.org"
    weight = 60
